### ISSUE TITLE
ignore by class

### ISSUE THREAD

**Issue by ar53n** [wellyshen/react-cool-onclickoutside#170]
# Feature Request

## Describe the Feature

Hello, thank you for this package. Can we add this functionality [Ingore by class](https://github.com/Pomax/react-onclickoutside#marking-elements-as-skip-over-this-one-during-the-event-loop)? 

## Additional Information

Prevent all events inside the ignored class

**Comment by wellyshen** [comment]
@ar53n OK, I will add it.

**Comment by wellyshen** [comment]
@ar53n [Here](https://github.com/wellyshen/react-cool-onclickoutside/releases/tag/v1.4.0) you are.

**Comment by ar53n** [comment]
@wellyshen  Thank you very much helped!

**Comment by viperfx** [comment]
@wellyshen would it be possible to add some more generic like a selector?  So it can be used for classes, attributes and IDs?

**Comment by wellyshen** [comment]
@viperfx Great idea, I will do it when I have time.

**Comment by wellyshen** [comment]
@viperfx I have evaluated this issue. It's possible to support `class`, `id`, `attribute` via the **querySelector API**. But the querySelector API traverses downward from every specific element. For performance concerning, I think it's better to keep the current API design.
