### ISSUE TITLE
TypeError: Cannot read property 'contains' of undefined

### ISSUE THREAD

**Issue by tonoslav** [wellyshen/react-cool-onclickoutside#318]
# Bug Report

## Describe the Bug
During tests I keep getting this error, its because **classList** is **undefined**
https://github.com/wellyshen/react-cool-onclickoutside/blob/5424ba2f7cb8a68fc02ebf7a6e43977135bdf7eb/src/index.ts#L27

## Fix
from
```js
if (el.classList.contains(ignoreClass)) return true;
```

to
```js
if (el.classList && el.classList.contains(ignoreClass)) return true;
```

**Comment by wellyshen** [comment]
@tonoslav Thank you for reporting this bug, it should be fixed in the latest release.
