### ISSUE TITLE
『 Survey 』 Add option to call callback also wen Escape is pressed

### ISSUE THREAD

**Issue by jnachtigall** [wellyshen/react-cool-onclickoutside#559]
https://www.npmjs.com/package/use-dismiss seems to have this feature (but misses others):

https://github.com/brandonpittman/use-dismiss/blob/master/src/useDismiss.js#L26-L40

I guess having an option (prop) so that not only on click outside but also when Esc is pressed to close would be good. For instance, dropboxes or modales - or would it be better to have this separate as in https://www.npmjs.com/package/@accessible/use-key or https://www.npmjs.com/package/use-key-hook ?

**Comment by wellyshen** [comment]
@jnachtigall Sorry for the late. Currently, the position of this package is focusing on the `on click outside` event. But I'll leave this issue for collecting the opinion of how many developers need this feature along with the click outside event. Thanks!
