### ISSUE TITLE
Detect clicks on iframes

### ISSUE THREAD

**Issue by bradvogel** [wellyshen/react-cool-onclickoutside#575]
Currently when clicking outside of an element, if you're clicking on an iframe element, this library will not detect that click. It would be nice if it did.

See the `detectIFrame ` feature of https://www.npmjs.com/package/v-click-outside

**Comment by wellyshen** [comment]
@bradvogel Nice feature, I will survey it soon.

**Comment by wellyshen** [comment]
@bradvogel This feature has been released in [v1.6.0](https://github.com/wellyshen/react-cool-onclickoutside/releases/tag/v1.6.0), thanks bro 👍🏻

**Comment by bradvogel** [comment]
Excellent, thanks!!
