### ISSUE TITLE
How to stop event bubbling ?

### ISSUE THREAD

**Issue by debotos** [wellyshen/react-cool-onclickoutside#635]
```js
const formContainerRef = useOnclickOutside(
  (e) => {
	console.log('Clicked outside...', e)
	e.stopPropagation()
  },
  { disabled: disableOutsideClickHandler, excludeScrollbar: true }
)
```

e.stopPropagation() not working here. Also e.nativeEvent is undefined.
Please help. Thanks.

**Comment by wellyshen** [comment]
@debotos Does it happen in v1.5.9?

**Comment by masonlee** [comment]
I don't know if this will help, but on v1.6.1 on iOS webkit, I have been having trouble stopping the touch events. Not sure if it's me, or some bug. My code worked fine on desktop, though, even without a "e.stopPropagation()" call, as OP has above.  I was hoping to use the useOnclickOutside function to close a modal on touch outside and remove it and its blur background overlay, but although the dialog and background do get removed, the outside touch seems to immediately trigger an onClick in the layer beneath it.  I haven't gone deep into debugging it, apologies.  Pressed for time, I solved the outside touch another way.  (Looks like a nice lib, btw! congrats!)

**Comment by wellyshen** [comment]
Close due to inactive, if this issue still bothers you guys, feel free to tell me.
