### ISSUE TITLE
v1.6.0 doesn't work with multiple refs

### ISSUE THREAD

**Issue by DmitryScaletta** [wellyshen/react-cool-onclickoutside#636]
# Bug Report

## Describe the Bug

v1.6.0 doesn't work with multiple refs
v1.5.9 works fine

## How to Reproduce

1. Go to [CodeSandbox demo](https://codesandbox.io/s/dank-shape-om9jo?file=/src/App.tsx) 
2. Click on "Open Dropdown" button
3. Click on the dropdown div (with red border) or "Click Here" button

## Expected Behavior

It shouldn't trigger callback function.

## Your Environment

- Device: PC
- OS: Windows
- Browser: Chrome
- Version: 89.0.4389.82 (Official Build) (64-bit)

**Comment by wellyshen** [comment]
@DmitryScaletta Thank you, I will fix it soon.

**Comment by wellyshen** [comment]
@DmitryScaletta It has been fixed via the [v1.6.1](https://github.com/wellyshen/react-cool-onclickoutside/releases/tag/v1.6.1)
