### ISSUE TITLE
ignore class should be able to ignore click events on chilldren of the ignored class

### ISSUE THREAD

**Issue by ogheneovo12** [wellyshen/react-cool-onclickoutside#685]
# Feature Request
ignore class should be able to ignore click events on children of the ignored class

## Describe the Feature
Ignore class only ignores click events of the elements class passed in, I would love if I could be able to specify that all click events on the children of that element are also ignored

## A clear and concise description of what you want and what your use case is.
 I would love if I could be able to specify that all click events on the children of that element are also ignored, I have a popup on a map that makes use of this hook, when clicked it opens a sidebar drawer, whenever the user interacts with the drawer, the react onClickOutside get's triggered, which in turns closes the popup, and that's not the behaviour I want.
what I want is for the popup to stay open, even while the user interacts with the drawer and all its children.

**Comment by wellyshen** [comment]
@ogheneovo12 This hook should support this feature already. Can you give me a minimal reproduced code via codesandbox or repo for debugging?

**Comment by wellyshen** [comment]
@ogheneovo12 We already support this feature. If there's an issue please provide a reproduced code via Codesandbox or GitHub repo.
