### ISSUE TITLE
Support HTMLElement for the "refs" option

### ISSUE THREAD

**Issue by ManuDoni** [wellyshen/react-cool-onclickoutside#762]
# Feature Request

## Describe the Feature

Make this hook compatible with `react-popper` making the `refs` option work also for HTMLElement and not just refs.

## Describe the Solution You'd Like

Just pass in HTMLElement(s) like they were refs.

## Describe Alternatives You've Considered

I didn't find any alternatives other than making my own hook from scratch, but I don't know how and I want to continue to use it in my projects also for this use case.

## Additional Information
This may be helpful: https://github.com/Andarist/use-onclickoutside/pull/12/files

When using `react-popper` we should create refs using `useState` rather than `useRef`.
See this example:
```js
function NotificationManager({user}) {
    const [notifications, notificationsDispatch] = useNotifications();
    const [showNotifications, setShowNotifications] = useState(false);
    const [referenceElement, setReferenceElement] = useState(null); //this is managed as a state, not a ref
    const [popperElement, setPopperElement] = useState(null); //this is managed as a state, not a ref
    const {styles, attributes} = usePopper(referenceElement, popperElement);
    useOnclickOutside(() => setShowNotifications(false), {
        refs: [referenceElement, popperElement] //I wish this could work
    })

    return (
        <>
            <div className="relative cursor-pointer" onClick={() => setShowNotifications(o => !o)} ref={setReferenceElement}>
                <UserAvatar user={user} bordered size={8}/>
            </div>

            {showNotifications &&
            <div className="notifications-menu" ref={setPopperElement} style={styles.popper} {...attributes.popper}>
                (notifications list)
            </div>
            }
        <>
    );
}
```

**Comment by wellyshen** [comment]
@ManuDoni You can share whatever ref that you want as follows:

```js
const [popperElement, setPopperElement] = useState(null);
const ref = useOnclickOutside(() => setShowNotifications(false));

const setRef = (el) => {
  setPopperElement(el);
  ref(el);
}

return <div ref={setRef} />;
```

**Comment by ManuDoni** [comment]
Wow, thank you! You solved my issue.
I only had to wrap `setRefs` inside a `useCallback` otherwise React goes into an infinite loop of renders
