### ISSUE TITLE
excludeScrollbar: true not working

### ISSUE THREAD

**Issue by ddc-enrique** [wellyshen/react-cool-onclickoutside#852]
# Bug Report

excludeScrollbar: true not working

## Describe the Bug

I'm using the option `excludeScrollbar: true`, but still if I click on the scrollbar it execute useOnClickOutside

## Expected Behavior

if I enable the option and I click on the scrollbar it should not execute the callback inside useOnClickOutside

## Your Environment

- Device: [Lenovo ThinkPad]
- OS: [Ubuntu]
- Browser: [Chrome]
- Version: [96.0.4664.45]

**Comment by wellyshen** [comment]
@ddc-enrique Sorry for the late. Did you click the scrollbar of the browser's viewport?

**Comment by wellyshen** [comment]
Close due to inactive.
